### ISSUE TITLE
Help in setting up

### ISSUE THREAD

**Issue by prudhvir3ddy** [haroldadmin/MoonShot#23]
@haroldadmin 
can you please include in docs what google-services are you using ?

and how to recreate my own keys for the project.

**Comment by haroldadmin** [comment]
Hey @prudhvir3ddy, glad to see you're interested in the project.

The app uses Firebase Crashlytics. I'm assuming you're familiar with how to setup a new Firebase project. In case you are not, you should create a new project on the [Firebase Console](https://console.firebase.google.com) using your Google Account. After the setup, you will have a chance to download the `google-services.json` file associated with the project you just created. Download this `google-services.json` file and place it in the `app/` folder, and rebuild. Your project should build successfully after this.

I should add these instructions to the project's README too. Happy exploring!
