### ISSUE TITLE
Update to Kotlin 1.4

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/MoonShot#31]
Update the project to use [Kotlin 1.4](https://kotlinlang.org/docs/reference/whatsnew14.html) to stay up to date with the latest changes.

The new type inference algorithm might break a few things which will need to be fixed before merging.

**Comment by ankitksh81** [comment]
Hey @haroldadmin, If I work on this issue, Will I also have to fix the issue with the type inference algorithm?
I'm interested in this one. Do let me know.

**Comment by haroldadmin** [comment]
I'm glad you're interested in working on the issue. I expect that there will be very few problems (if at all) with the new type inference algorithm in Kotlin 1.4. That being said, it is still a possibility that a few issues arise. They will need to be fixed. 

Honestly, though, this should not be a huge problem, as I'm here to help you out along the way. Additionally, there is an automated migration assistant tool in Android Studio which is triggered after updating a project to Kotlin 1.4.

**Comment by ankitksh81** [comment]
Alright then, I'm willing to give it a shot.

**Comment by haroldadmin** [comment]
If you want to do it as a part of Hacktoberfest, you might want to wait until October 1 for submitting a PR. Otherwise, feel free to do it whenever you can. Assigning the issue to you.

**Comment by ankitksh81** [comment]
Yeah sure, I will wait until October.

**Comment by ankitksh81** [comment]
@haroldadmin, I need help with some issues while importing the project.

**Comment by haroldadmin** [comment]
Please describe the issue.

**Comment by ankitksh81** [comment]
There are few warnings,
Gradle sync failed: Cannot query the value of this provider because it has no value available.
And the other is related with the android sdk license since I installed android studio for the 1st time on this machine, which I will figure out.

**Comment by ankitksh81** [comment]
Hi, Sorry to inform you but I don't think I will be able to work on this issue right now.
I don't have the system in which I have all the things setup, This is a new system and I'm getting all kinds of errors, So I would be better if you assign this task to someone else. Sorry again.

**Comment by DeKaN** [comment]
@haroldadmin Can I take this issue?

**Comment by haroldadmin** [comment]
@DeKaN Sure! Please go ahead.
