### ISSUE TITLE
Would be cool if we could customise the app to give notifications a custom amount of time before launch

### ISSUE THREAD

**Issue by spookyuser** [haroldadmin/MoonShot#4]
Hey, the app is amazing and I really want to start using it completely instead of spacexnow. But, one of the most important features I miss from that app is being notified a week or a day before the launch that there is going to be a lauch. So it would be really cool if this app could also do that 😄

**Comment by haroldadmin** [comment]
Thank you for the feature request. I too have been thinking about adding this feature. I'll try to include it in the next release.

**Comment by haroldadmin** [comment]
Based on your feedback, I think the following three notifications would be useful:
1. One week before the launch
2. One day before the launch
3. Just before the launch (the kind that the app currently has)

I want these notifications to be user customizable. If someone doesn't want to receive them, then they should be able to opt out of them. For this, I have the following two approaches in mind:

* Adding a toggle in the app settings
This would work, but I think it would create clutter in the app settings without providing too much customizability.

* Create separate notification channels for these different types of notifications. This way the users can customize which ones they want to receive in the Android Settings app. This approach also allows for customization of notification tones for each channel and other things.

In-app settings would be simpler to use, but the notification channels approach is more customizable. Which one do you think is the better option? @spookyUnknownUser

**Comment by spookyuser** [comment]
Wow that would be amazing. In terms of the timeframes I think one week, one day and just before would be perfect options. 

Notification channels are probably a safe bet, because yes you would absolutely want to be able to choose which notifications you want. And toggles would definitely create a lot of clutter in the settings. 

So between these two options I would pick the notification channels 😀

But the notification channels could also become cluttered, if you ever want to extend the list of time options in the future above the three we mentioned, then the notification channel list becoming longer and longer probably also wouldn't be great. 

I don't know if this would work, but I was just thinking now that maybe a "notification intensity slider" could work in the settings as a third way of doing this. Where you could slide to the left and right to indicate less or more notifications. On one end could be a week out and on the other would be 24 hours or even an hour out. If you slide it all the way to a week then you would get all notifications but if you only slide it to 1 hour then you would only get notifications before the launch. The question with this would be if it's always true that people who want to be notified a week before also want to be notified an hour before. I think, though, that this is probably true. If you want a notification far in advance, then you probably also want one soon before. If this works, then you would only need one notification channel for all launches.

**Comment by haroldadmin** [comment]
I personally like the Notification Channels solution better, but unfortunately they are only supported on devices running Oreo and above. I'll go with the in-app settings option then. Separate channels, would still of course exist on devices with Oreo or higher.

I'm not sure if the notification intensity slider is a good idea, though. I don't think it would be intuitive to everyone what the "intensity" of the slider implies. It's ambiguous, and does not allow fine-grained control.

**Comment by haroldadmin** [comment]
Added in Version 0.8.0. I'll push out an update to the alpha channel today. Please open a new issue on this repository if find any bugs with the system.

The alpha channel is for closed testing, so if you want to join it please send me your email address on a [Twitter DM](https://twitter.com/haroldadmin). Or if you can wait, I'll push it out to the beta channel in a couple of days if there are no new crashes.

**Comment by spookyuser** [comment]
Amazing, thank you so much!
